### ISSUE TITLE
Não é possível criar uma reserva quando o documento do cliente está cadastrado na Azul, mas o nome não corresponde ao cadastrado

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#15]
**Problema**
Quando tento fazer uma reserva com um documento de um cliente cadastrado em um programa da Azul, mas o nome não é mandado exatamente como o cadastrado, a api retorna o erro:
`{
  "notifications": [
    {
      "code": "CustomProgram.NotMatch",
      "message": "Passenger name does not match within informed Customer Program."
    }
  ]
}`

**Para reproduzir:**
1. Execute um POST na API 'api/v1/token'.
2. Execute um POST na API 'api/v1/authenticate'.
3. Execute um POST da API 'api/v1/airSearch' com qualquer trecho:.
4. Execute um  POST da API 'api/v1/order' com o seguinte payload
`{
  "offers": [
    {
      "journeyKey": "",//Qualquer Journey
      "fareKey": ""//Qualquer Fare
    }
  ],
  "passengers": [
    {
      "email": "fulano@teste.com",
      "name": {
        "first": "*****",//Nome Diferente do cadastrado no documento no programa Azul
        "last": "*****"//Nome Diferente do cadastrado no documento no programa Azul
      },
      "gender": "",
      "dateOfBirth": "",
      "nationality": "BR",
      "phone": "",
      "type": "ADT",
      "travelDocuments": [
        {
          "birthCountry": "BR",
          "issuingCountry": "BR",
          "number": "***********",//Numero de documento cadastrado em algum programa Azul
          "type": "CPF"
        }
      ],
      "iropContact": {
        "refused": true,
        "email": "",
        "mobile": ""
      }
    }
  ]
}`.
5. Apos isso é retornado o erro "502 - Bad Gateway" com mensagem  "Passenger name does not match within informed Customer Program.".

**Comportamento esperado**
Mesmo enviando dados diferentes do cadastrado na Azul, deveria ser possível criar uma reserva.

**Ambientes**
Ambientes testados: Produção e Homologação

**Comment by lisleyevelin** [comment]
Implementação realizada no ambiente de Produção no dia: 22/11/2023.
