### ISSUE TITLE
Problema ao emitir uma order

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#16]
**Descrevendo o bug**
Em alguns casos, que quando tento emitir uma order, mesmo mandando o valor correto para o pagamento dela, e a api me retornando balanceDue:0, é retornado um erro de pagamento faltando quando tento fazer o checkout da mesma

**Para reproduzir**
1. Execute um POST na API 'api/v1/token'.
2. Execute um POST na API 'api/v1/authenticate'.
3. Execute um POST da API 'api/v1/airSearch' com qualquer trecho:.
4. Execute um POST da API 'api/v1/order' para criar uma reserva com qualquer trecho e faça o checkout da mesma
5. Execute um POST da API 'order/management/api/v1/order/${recordId}'
6. Execute um POST da API 'order/payments/api/v1/order/payments' como valor certo da order, e tendo como response:
`{ "totals": {
    "amount": xxxx.xx,
    "balanceDue": 0,
    "discountedAmount": 0
  },
  "currencyCode": "BRL"
}`
7. Apos isso, execute um POST na rota `order/management/api/v1/order/${recordLocator}/checkout` para fazer o checkout e recebo o seguinte erro:
`{ "notifications": [
    {
      "code": "Payments.MinimumRequired",
      "message": "Payments must contemplate all journey fares, travel fees and taxes."
    }
  ]
},`

**Comportamento esperado**
Como o valor de balanceDue retornado é 0, conseguir emitir a passagem. Caso exista algum valor a mais a ser pago, retornar nesse campo para clarificar o que esta faltando

**Ambiente**

Ambiente usado: Produção.

**Comment by lisleyevelin** [comment]
Detectamos que existia um erro no fluxo de categorização e nosso time de desenvolvimento já aplicou uma correção que corrige este problema.
Implementação realizada no ambiente de Produção no dia: 06/12/2023.
