### ISSUE TITLE
Erro de acesso JAVA

### ISSUE THREAD

**Issue by diegobernardinelliSAVN** [voeazul/middleware-b2b#17]
**Describe the bug**
Recebendo erro de timeout em qualquer requisição (independente do endpoint, header e body correto ou nao).

**To Reproduce**
Aplicação gerada com o Springboot 3 (já tentei tbm com a versão 2)
JDK 8 ou 17 (dependendo da versao do springboot escolhida)

Configurando os objetos RestTemplate, HttpRequest e WebClient (todos deram o mesmo problema)

Algumas mensagens de erro dependendo da forma de conexao:
1-
java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)

2-
Caused by: java.io.EOFException: EOF reached while reading

3-
java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[na:na]

Vocês já presenciaram este problema ou se tem que efetuar alguma configuração diferenciada para o webservices Azul?

**Comment by lisleyevelin** [comment]
Boa tarde, Diego
Devido a validação de segurança, para complementar o processo de acesso as APIs do barramento, além da subscription key, é necessário enviar o header em todas as requisições das APIs da AZUL:  User-Agent, com o seguinte valor: salesb2b/nome_da_agencia, sendo o nome_da_agencia, a agencia em questão que está fazendo a integração.
Por exemplo: salesb2b/xpto_viagens.

Favor seguir com o procedimento citado e informar por aqui o resultado obtido, tá?
