### ISSUE TITLE
Reserva criada com nome diferente do enviado

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#20]
**Descrevendo o bug**
Foi enviado um nome na hora de gerar a reserva, mas a reserva foi gerado com outro nome

**Para Reproduzir**
1. Faça um processo de compra normal ate a hora de enviar dados do passageiro
2. Na requisição de POST 'api/v1/order' para criar a reserva, envie o documento de uma pessoa cadastrada em um programa da Azul mas o nome diferente do cadastrado
3. Reserva é criada com o nome cadastrado, e não com o nome enviado

**Comportamento Esperado**

A reserva ser criada com o nome enviado

**Ambiente**

Ambiente usado: Produção

**Contexto Adicional**

Cliente não conseguiu embarcar devido a essa diferença e foi necessário fazer outra reserva

**Comment by 5by5-cfilho** [comment]
Boa tarde @Andremoreira06, esse comportamento é o esperado por nosso Middleware B2B.

Durante a emissão, caso seja detectado o envio do programa TudoAzul ou documento vinculado à um cadastro no programa, é realizada uma validação de proximidade do nome, e caso essa validação seja positiva, o nome do passageiro é sempre substituído para o nome cadastrado no programa. 

Isso se faz necessário para garantirmos que o passageiro receberá seus benefícios do programa.

Casos específicos como esse, o cliente deve entrar em contato com o time do TudoAzul e solicitar a correção de seu nome cadastrado no programa, caso contrário ele terá o mesmo problema seja em emissões por sua agencia ou através de nosso site e callcenter.

**Comment by Andremoreira06** [comment]
Boa tarde @5by5-cfilho, entendi, obrigado pela resposta

Em relação ao prejuízo gerado por essa reserva, como podemos olhar?

**Comment by 5by5-cfilho** [comment]
Olá @Andremoreira06 , solicito que entre em contato direto com nosso departamento comercial para explicar a situação e endereçar a melhor solução
