### ISSUE TITLE
Clientes com problema no checkIn

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#25]
Alguns clientes relataram que tiveram problemas para fazer CheckIn virtual de compras feitas pela integração e nos foi relatado que não estamos enviando o telefone de contato, mas validei no código e estamos enviando no campo "phone" dentro de cada passageiro.

`{
  "offers": [
    {
      "journeyKey": "",
      "fareKey": ""
    }
  ],
  "passengers": [
    {
      "email": "email@email.com",
      "name": {
        "first": "Fulano",
        "last": "Silva"
      },
      "gender": "Male",
      "dateOfBirth": "1950-01-01",
      "nationality": "BR",
      "phone": "31999999999",
      "type": "ADT",
      "travelDocuments": [
        {
          "birthCountry": "BR",
          "issuingCountry": "BR",
          "number": "",
          "type": "CPF"
        }
      ],
      "iropContact": {
        "refused": false,
        "email": "email@email.com",
        "mobile": ''
      }
    }
  ],
  "promotionCode": ""
}`

Com esse payload, consigo criar a order, mas me retorna uma notificação de erro:

`"notifications": [
    {
      "code": "RequestFailed.ContactError",
      "message": "Your Order request was succefully processed, but the informed booking contact has errors."
    }
  ]`
  
 A qual campo ela esta se referindo?
 
 E também vi na documentação que ha um campo novo de contato na hora de criar a order:
 
 `"contact": {
        "address": {
            "lineOne": "string",
            "lineTwo": "string",
            "lineThree": "string",
            "country": "string",
            "provinceState": "string",
            "city": "string",
            "postalCode": "string"
        },
        "email": "string",
        "companyName": "string",
        "name": {
            "first": "string",
            "middle": "string",
            "last": "string",
            "title": "MS",
            "suffix": "FO"
        },
        "phones": [{
            "number": "string",
            "type": "Other"
        }]
    },`
 
 Qual a finalidade dele?
 
E em qual desses campos deveríamos enviar o telefone para que seja possível que o cliente consiga fazer o CheckIn virtual?

**Comment by lisleyevelin** [comment]
Boa noite, André

A equipe técnica está avaliando sobre a questão da notificação que está sendo apresentada,  "notifications": [ { "code": "RequestFailed.ContactError", "message": "Your Order request was succefully processed, but the informed booking contact has errors." } ]
Porém de imediato acreditamos que se você começar a enviar no GET Order o campo opcional: Contact preenchido pelo menos o campo: Phone com as informações abaixo, já irá resolver a questão do erro e também a questão do Checkin virtual.
     "phones": [{
                "type": "Home",
                "number": "string" -- inserir telefone
            }]
Iremos alterar esta informação no swagger pois hoje esta no GET Order >> Campo: Contact >> Phone com o "type" = Other

Identificamos uma configuração pendente no cadastro da Onfly, e já informei o Ian, para inserir a informação pendente.
