### ISSUE TITLE
Erro 503Service Unavailable

### ISSUE THREAD

**Issue by tadashisuto** [voeazul/middleware-b2b#28]
Erro 503Service Unavailable na chamada {{urlAuthorization}}/api/v1/token

![image](https://github.com/voeazul/middleware-b2b/assets/163872368/01255ebc-4291-47ba-a260-0c8f5cc4911a)

**Comment by lisleyevelin** [comment]
Bom dia, Tadashi!
Realmente estamos com uma instabilidade em nosso ambiente de STG - Testes devido a uma manutenção não prevista, não temos previsão de resolução. Mas assim que o mesmo for tratado lhe informo.

**Comment by IanLima01022021** [comment]
Chamado fechado, estamos a disposição.

**Comment by IanLima01022021** [comment]
.

**Comment by lisleyevelin** [comment]
Pessoal, acabei de executar o método authentication no ambiente de Testes e obtive retorno satisfatório.
Aparentemente a instabilidade foi tratada.
Favor prosseguir com a execução, e nos informar caso apresente novos problemas.
Obrigada
