### ISSUE TITLE
Valor de INF para reservas INTER está incorreto

### ISSUE THREAD

**Issue by TelmaMontone** [voeazul/middleware-b2b#29]
Gostaríamos de abordar uma questão específica relacionada à cobrança de tarifas para passageiros INF (bebês) em voos internacionais.

Conforme observado nas regras publicadas no site da Azul, é estipulado que o valor da tarifa para INF deve corresponder a 10% da tarifa do passageiro adulto (ADT). No entanto, identificamos que, atualmente, essa prática não está sendo consistentemente aplicada em nossos sistemas.

![INF para INTER](https://github.com/voeazul/middleware-b2b/assets/155120401/e06e6a51-3683-4810-ac89-93a209abcbae)

Essa discrepância pode potencialmente gerar confusão, pois esperam que a cobrança do INF seja alinhada com as diretrizes divulgadas.

**Comment by IanLima01022021** [comment]
Bom dia.
Chamado em analise.

**Comment by IanLima01022021** [comment]
Telma, boa tarde.
A composição da tarifa do adulto é a soma de algumas variáveis que não entram na composição da tarifa do INF, por isso podemos ter diferença e é normal. Podem assumir o valor retornado da API sem realizar nenhum cálculo.
