### ISSUE TITLE
Tarifa de CHD não está igual à tarifa de ADT quando há aplicação de acordo

### ISSUE THREAD

**Issue by TelmaMontone** [voeazul/middleware-b2b#30]
Estamos notando uma discrepância nos valores das tarifas, especificamente quando se trata de crianças (CHD) em voos com credenciais de acordo. A questão é: essa diferença é comum? E mais importante, nossos sistemas estão desconsiderando a informação do acordo ao calcular essas tarifas?

![CHD difere de ADT quando tem acordo](https://github.com/voeazul/middleware-b2b/assets/155120401/ead3606b-faa1-4a30-94b0-20b2acd1930e)

Precisamos entender melhor por que essa disparidade está ocorrendo e se estamos seguindo corretamente as diretrizes estabelecidas pelos acordos comerciais. Será que há algum ajuste necessário em nossos processos ou sistemas para garantir que as tarifas de crianças reflitam corretamente os termos dos acordos?

**Comment by IanLima01022021** [comment]
Telma, bom dia.
Realizei o teste com 1 ADT e 1 CHD incluindo um promocode e as tarifas retornaram corretamente conforme logs em anexo.
[REQUEST ISSUE 30.txt](https://github.com/voeazul/middleware-b2b/files/14666868/REQUEST.ISSUE.30.txt)
[RESPONSE ISSUE 30.txt](https://github.com/voeazul/middleware-b2b/files/14666869/RESPONSE.ISSUE.30.txt)

Acredito que possa ter sido um caso pontual mas peço para testarem novamente por gentileza.
