### ISSUE TITLE
Endpoint Order By Record Locator

### ISSUE THREAD

**Issue by TelmaMontone** [voeazul/middleware-b2b#31]
Ao acessar o endpoint Order By Record Locator, surge a dúvida sobre onde encontrar as informações sobre a entidade que está vendendo e operando o voo. Podemos sempre presumir que é a Azul que estará vendendo o voo?

Agradeço a confirmação sobre essa questão para garantir que nossas análises estejam corretas e alinhadas com as informações fornecidas pelo sistema.

**Comment by carlos-inacio-voeazul** [comment]
Boa tarde Telma,

todos os voos ofertado em nosso Middleware são vendidos pela pela Azul.

Em caso de voos vendidos pela Azul, mas operados por outras parceiras (Codeshare), dentro da estrutura de Segment teremos o objeto "operatingIdentifier" preenchido com o numero de voo da parceira e código da cia
