### ISSUE TITLE
Inserir informação no endpoint AirSearch no objeto organizationFeeRules

### ISSUE THREAD

**Issue by TelmaMontone** [voeazul/middleware-b2b#32]
Gostaria de destacar uma oportunidade de aprimoramento no sistema que pode otimizar consideravelmente nossos processos de desenvolvimento.

Atualmente, ao acessar o endpoint AirSearch e verificar o objeto organizationFeeRules, notamos que a informação fornecida sobre a cobrança de DU (DUFEE) é genérica e aplicada a todos os passageiros, incluindo INF.

Durante a reunião de sexta-feira, identificamos a necessidade de especificar para quais tipos de passageiros a cobrança do DUFEE é válida. No entanto, ao analisar apenas a API, não conseguimos determinar facilmente para quais passageiros essa cobrança deveria ser aplicada.

O objeto hoje vem assim:
 
"organizationFeeRules": {
                "type": "DUFEE",
                "overridable": false,
                "percentage": 10,
                "minimal": 40.0,
                "currencyCode": "BRL"
            }
 
A sugestão é que ele venha assim:
 
"organizationFeeRules": {
                "type": "DUFEE",
                "passengerType": ["ADT", "CHD"]
                "overridable": false,
                "percentage": 10,
                "minimal": 40.0,
                "currencyCode": "BRL"
            }
 
 
Ou algo parecido com isso

Sugerimos, portanto, que seja considerada a adição na API dos tipos de passageiros que devem receber a cobrança do DUFEE. Essa melhoria garantirá uma maior clareza e precisão nas informações fornecidas, facilitando o processo de desenvolvimento e garantindo uma aplicação consistente das regras de cobrança.

**Comment by lisleyevelin** [comment]
Boa tarde, Telma
Esta solicitação já foi encaminhada para o PO do projeto B2B, e o mesmo será priorizado em Sprints futuras.
 História:742916
