### ISSUE TITLE
Problema informações de contato

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#33]
**Descrevendo o bug**
Quando enviamos os dados de contato no campo 'contacts' na rota "/order/api/v1/order", eles estão sendo ignorados e estão sendo usados os dados cadastrados na Azul, tambem aconteceu um caso em que o telefone usado no campo "phone" do traveler foi para o campo de retorno 'contacts' na rota "/order/management/api/v1/order/:OrderId" e foi misturado informações da agencia com informações do cliente com o retorno no seguinte formato:

`"contacts": [
                {
                    "type": "Other",
                    "address": null,
                    "email": "EMAIL DO PASSAGEIRO",
                    "companyName": null,
                    "name": {
                        "first": "NOME DO GESTOR DA ONFLY",
                        "middle": null,
                        "last": "NOME DO GESTOR DA ONFLY",
                        "title": null,
                        "suffix": null
                    },
                    "phones": [
                        {
                            "type": "Home",
                            "number": "TELEFONE DO PASSAGEIRO"
                        }
                    ]
                },`

**Comportamento esperado**
Quando enviado dados de contato eles serem levado em consideração na criação da order, e que dados do cliente não sejam misturados com dados da agencia

**Ambiente**

Ambiente usado: Homologação e Produção.

**Contexto adicional**
Devido a mistura de informações, foi enviado uma mensagem para o cliente em vez de para a Agencia e gerou um desconforto com o cliente

**Comment by IanLima01022021** [comment]
Andre, boa tarde.
Poderia por gentileza anexar os logs das chamadas para que possamos analisar.

**Comment by IanLima01022021** [comment]
Andre, boa tarde.
Favor mandar os logs para a chave: suporteb2b@voeazul.com.br

**Comment by lisleyevelin** [comment]
Boa tarde, André
Realizamos a análise nos logs enviados via email, e contatamos que não existe nada de errado com as informações enviadas nos requests. Identificamos que os dados se perderam em outros sistemas. O Ian do comercial irá levantar nestas outras frentes para identificar o que pode ter ocorrido. è importante deixar claro que o Barramento B2B está com o comportamento correto.

**Comment by carlos-inacio-voeazul** [comment]
Issue está sendo encerrada pois o problema detectado não é do nosso Middleware B2B, e o mesmo será tratado em um fórum a parte junto do nosso departamento Comercial e demais sistemas envolvidos
