### ISSUE TITLE
[Dúvida] - Funcionamento do Token

### ISSUE THREAD

**Issue by caraujoufsm** [voeazul/middleware-b2b#34]
Boa tarde,
Conforme solicitado, encaminho as dúvidas quanto ao funcionamento do token.

1 - Qual seria a quantidade de tokens máxima que podemos autenticar? No caso o limite possível?
 
2 - Quantos chamados posso fazer com o mesmo token? Considerando chamados concomitantes.

**Comment by carlos-inacio-voeazul** [comment]
Boa tarde,

1 - No momento não há um limite definido de tokens que podem ser utilizados simultaneamente por subscription key.

2- Nossa API é statefull (armazena dados de estado de reservas) e não é possível realizar chamadas concomitantes com um mesmo token. Para realização de atividades simultâneas, recomendamos que cada atividade tenha sua própria sessão autenticada (um mesmo usuário pode se autenticar simultaneamente, desde que em tokens diferentes)
