### ISSUE TITLE
Erro ao mandar refused como true em IropContact

### ISSUE THREAD

**Issue by erikaaraissaqwe** [voeazul/middleware-b2b#36]
**Cenário**

Ao enviar o objeto iropContact como refused true obtemos um erro que é necessário preencher os campos email e mobile

![image](https://github.com/voeazul/middleware-b2b/assets/45106624/72dfe8ca-0b9e-4bba-abaa-c0da8f9d7e59)

Porém, ao preencher os campos email e mobile e o refused como true também obtemos um erro:

![image](https://github.com/voeazul/middleware-b2b/assets/45106624/20f336a5-171b-4ec8-b677-6a678e0a8281)

Também temos erro ao não enviar o objeto IropContact, por mais que a documentação afirme que não é obrigatório é retornado o erro:

 The 'Passengers.IropContact' is required., java.lang.Exception: RequiredField.IropContact - The 'Passengers.IropContact' is required.
 
 
![image](https://github.com/voeazul/middleware-b2b/assets/45106624/129b021b-f841-43b7-9a67-904001f09305)

**Passos para a reprodução**

1. Ao realizar a chamada POST 'api/v1/order' usando o seguinte payload:
```
{
    "offers": [{
            "journeyKey": "QUR_Mjc4Mn4gfn5DR0h_MDQvMTYvMjAyNCAxMjoxMH5TRFV_MDQvMTYvMjAyNCAxMzoxNX5_",
            "fareKey": "MH5Vfn5BRH5VMTIxQ1gxQX4yMUNYfn4wfjR_flghMw--"
        }
    ],
    "passengers": [{
            "nationality": "BR",
            "gender": "Male",
            "dateOfBirth": "1980-12-12T00:00:00",
            "phone": " 984598494",
            "email": "argoemailunico@gmail.com",
            "type": "ADT",
            "name": {
                "first": "AntOnio",
                "middle": "",
                "last": "Souza",
                "title": "MR",
                "suffix": ""
            },
            "travelDocuments": [{
                    "type": "CPF",
                    "number": "06227896004",
                    "birthCountry": "BR",
                    "issuingCountry": "BR"
                }, {
                    "type": "RG",
                    "number": "78364499",
                    "birthCountry": "BR",
                    "issuingCountry": "BR"
                }, {
                    "type": "PASSPORT",
                    "number": "834567887",
                    "birthCountry": "BR",
                    "issuingCountry": "BR",
                    "expirationDate": "2025-12-10T00:00:00"
                }
            ],
            "iropContact": {
                "refused": true,
                "mobile": " 984598494",
                "email": "argoemailunico@gmail.com"
            }
        }
    ],
    "contact": {
        "address": {
            "lineOne": "Teste Modificação",
            "lineTwo": "CERQUEIRA CESAR",
            "lineThree": "",
            "country": "BR",
            "provinceState": "SP",
            "city": "SAO PAULO",
            "postalCode": "01418102"
        },
        "email": "tms@teste.com",
        "companyName": "Teste Azul MS",
        "name": {
            "first": "Teste",
            "middle": "",
            "last": "SOLUTIONS",
            "title": "MR",
            "suffix": ""
        },
        "phones": [{
                "number": "1148586078",
                "type": "Home"
            }
        ]
    },
    "promotionCode": ""
}
```

2. O erro:

```
{
    "notifications": [{
            "code": "InvalidField.IropContact.Email",
            "message": "The 'Passengers.IropContact.Email' cannot be informed when Passengers.IropContact.Refused is True."
        }, {
            "code": "InvalidField.IropContact.Mobile",
            "message": "The 'Passengers.IropContact.Mobile' cannot be informed when Passengers.IropContact.Refused is True."
        }
    ]
}
```

 é retornado.

--------

1. Ao realizar a chamada POST 'api/v1/order' usando o seguinte payload:

```
{
    "offers": [{
            "journeyKey": "QUR_NjA1NH4gfn5DR0h_MDQvMTYvMjAyNCAxMDo1MH5TRFV_MDQvMTYvMjAyNCAxMTo1NX5_",
            "fareKey": "MH5Vfn5BRH5VMTIxQ1gxQX4yMUNYfn4wfjR_flghMw--"
        }
    ],
    "passengers": [{
            "nationality": "BR",
            "gender": "Male",
            "dateOfBirth": "1980-12-12T00:00:00",
            "phone": " 984598494",
            "email": "argoemailunico@gmail.com",
            "type": "ADT",
            "name": {
                "first": "AntOnio",
                "middle": "",
                "last": "Souza",
                "title": "MR",
                "suffix": ""
            },
            "travelDocuments": [{
                    "type": "CPF",
                    "number": "06227896004",
                    "birthCountry": "BR",
                    "issuingCountry": "BR"
                }, {
                    "type": "RG",
                    "number": "78364499",
                    "birthCountry": "BR",
                    "issuingCountry": "BR"
                }, {
                    "type": "PASSPORT",
                    "number": "834567887",
                    "birthCountry": "BR",
                    "issuingCountry": "BR",
                    "expirationDate": "2025-12-10T00:00:00"
                }
            ],
            "iropContact": {
                "refused": true
            }
        }
    ],
    "contact": {
        "address": {
            "lineOne": "Teste Modificação",
            "lineTwo": "CERQUEIRA CESAR",
            "lineThree": "",
            "country": "BR",
            "provinceState": "SP",
            "city": "SAO PAULO",
            "postalCode": "01418102"
        },
        "email": "tms@useargo.com",
        "companyName": "Teste Azul MS",
        "name": {
            "first": "Teste",
            "middle": "",
            "last": "SOLUTIONS",
            "title": "MR",
            "suffix": ""
        },
        "phones": [{
                "number": "1148586078",
                "type": "Home"
            }
        ]
    },
    "promotionCode": ""
}

```

2. O erro:

```
{
    "errors": {
        "passengers[0].iropContact.email": ["Required property 'email' not found in JSON. Path 'passengers[0].iropContact', line 1, position 721."],
        "passengers[0].iropContact.mobile": ["Required property 'mobile' not found in JSON. Path 'passengers[0].iropContact', line 1, position 721."]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-86acd6a35e140a08bf903d643f5377ae-d5f2b6114198c4dd-00"
} 
```

 é retornado.

**Cenários esperados**

- Que ao não enviar o campo IropContact a API retorne com sucesso.
- Que ao preencher como true o campo refused do IropContact não seja necessário enviar outros dados relacionados.

**Ambiente**
Homologação

**Comment by lisleyevelin** [comment]
Boa tarde, Erika
Estamos em análise técnica sobre o comportamento da API X SWAGGER e lhe retornaremos em  breve.

**Comment by lisleyevelin** [comment]
Bom dia, Erika
Segue respostas:

Cenário

1 - Ao enviar o objeto iropContact como refused true obtemos um erro que é necessário preencher os campos email e mobile
Resposta: Para este cenário deverá ser enviado da seguinte forma:
iropContact: { 
refused: true, 
email: "", 
phone: "" 
}

2 - Porém, ao preencher os campos email e mobile e o refused como true também obtemos um erro:
Resposta: Este comportamento está correto pois quando enviado o valor refused = true, quer dizer que será enviado dados de email e/ou telefone


3- Também temos erro ao não enviar o objeto IropContact, por mais que a documentação afirme que NÃO é obrigatório é retornado o erro de campo mandatório.
Resposta: Iremos regularizar a documentação do Swagger onde o campo Passengers.IropContact será definido como MANDATÓRIO.


Cenários esperados
Que ao não enviar o campo IropContact a API retorne com sucesso.
Resposta: Será alterado a documentação do Swagger e este campo será Mandatório

Que ao preencher como true o campo refused do IropContact não seja necessário enviar outros dados relacionados.
Resposta: Para este cenário deverá ser enviado da seguinte forma:
iropContact: { 
refused: true, 
email: "", 
phone: "" 
}

Observação iremos alterar também na documentação do Swagger dentro do iropContact DE: (refused = true, mobile = true, email = true)
PARA: (refused = false, mobile = false, email = false), os seguintes fluxos serão aceitos com a nova implementação:
{ refused: true } 
{ refused: true, email: "", phone: "" }
{ refused: false, email: "teste@teste.com.br", phone: "(00) 91111-2222" }
{ email: "teste@teste.com.br", phone: "(00) 91111-2222" }
