### ISSUE TITLE
Erro ao realizar a chamada /checkout em reservas internacionais

### ISSUE THREAD

**Issue by erikaaraissaqwe** [voeazul/middleware-b2b#38]
Cenário

Ao realizar a chamada /checkout para reservas internacionais estamos obtendo o erro:

`{"notifications":[{"code":"AgentOrder.NotAuthorized","message":"Agent is not authorized to commit order with invalid price status without requesting to override restrictions."}]}`

Passos para a reprodução

- Realizar reserva de VCP = ORY (round trip) com um ADT  no dia 03/abr à 05/abr
- A reserva ficará em hold pois o pagamento não será realizado ainda
- Realizar checkout

Response do POST order

`{"data":{"order":{"currencyCode":"BRL","organizationCode":"01402750","totals":{"amount":9046.31,"balanceDue":9046.31}}},"notifications":[]}`

Response do checkout

`{"notifications":[{"code":"AgentOrder.NotAuthorized","message":"Agent is not authorized to commit order with invalid price status without requesting to override restrictions."}]}`

Cenários esperados

Que o checkout seja concluído com sucesso para reservas internacionais em hold

Ambiente
Homologação

**Comment by lisleyevelin** [comment]
Boa tarde, Erika
 Entendi que você esta tentando criar uma reserva com voo internacional em Hold, e está executando as seguintes chamadas para a criação da reserva:
{{urlAuthorization}}/api/v1/token
{{urlUser}}/api/v1/authenticate
{{urlShopping}}/api/v1/airSearch
{{urlOrder}}/api/v1/order
{{urlOrder}}/api/v1/checkout - Aqui a Reserva e criada e fica em HOLD por não ter sido efetuado o pagamento.
Porém no erro descrito acima, esta claro que: O agente não está autorizado a confirmar pedidos com status de preço inválido sem solicitar a substituição das restrições.
Vi que esta utilizando a organização: 01402750, mas qual usuário?

Para a realização de pagamento de uma reserva em Hold,  os seguintes passos deverão ser seguidos:
{{urlOrderManagement}}/api/v1/order/:recordLocator
{{urlOrderPayments}}/api/v1/order/payments
{{urlOrderManagement}}/api/v1/order/:recordLocator/checkout

**Comment by erikaaraissaqwe** [comment]
O username é o 01402750ARG. O retorno do {{urlUser}}/api/v1/authenticate foi:

`{"data":{"sessionContext":{"pointOfSale":{"code":"01402750","name":"ARGO TESTE","currencyCode":"BRL"},"profile":"WebServiceAgent"}},"notifications":[]}
`

É necessário fazer algum outro fluxo antes do checkout? As reservas nacionais estão sendo finalizadas com sucesso com o mesmo fluxo em reserva em hold.

**Comment by lisleyevelin** [comment]
Iremos analisar o cadastro do usuário, pois aparentemente ele não tem permissão para criar reserva com voo internacional.

O fluxo para criação de reservas para voos nacionais ou internacionais são os mesmos.

**Comment by lisleyevelin** [comment]
@IanLima01022021, você pode por favor verificar a permissão do usuário: 01402750ARG, pois na criação de uma reserva onde o trecho escolhido são voos internacionais esta sendo apresentando a mensagem:
"O agente não está autorizado a confirmar pedidos com status de preço inválido sem solicitar a substituição das restrições."

**Comment by lisleyevelin** [comment]
Erika, boa tarde!! 
Favor me enviar via e-mail os logs completos desta execução para que seja possível que eu efetue a simulação do mesmo.
Obrigada

**Comment by IanLima01022021** [comment]
Pessoal, boa tarde.
Realizei um teste usando o usuário argo (01402750ARG) com os mesmos filtros informados na descrição e consegui criar a reserva. Anexo os logs da reserva que eu fiz.
[LOGS ARGO.txt](https://github.com/voeazul/middleware-b2b/files/14794080/LOGS.ARGO.txt)

Peço que alterem a senha do usuário para que possam usam novamente, orientação enviada por e-mail.
<img width="889" alt="Reserva Argo" src="https://github.com/voeazul/middleware-b2b/assets/143032135/23eeeb55-4947-418c-bcf9-09a3a8beaab2">

**Comment by erikaaraissaqwe** [comment]
Na nova tentativa, a reserva foi finalizada com sucesso.
