### ISSUE TITLE
Erro ao realizar a chamada /offer/quote

### ISSUE THREAD

**Issue by erikaaraissaqwe** [voeazul/middleware-b2b#40]
**Cenário**

Ao solicitar a cotação com um journeyKey e fareKey especificos obtemos o retorno com o farekey diferente do solicitado.

**Passos para a reprodução**

1. Execute a chamada POST para  'api/v1/token' API.
2. Execute a chamada POST para 'api/v1/authenticate' API.
3. Execeute a chamada POST para {{urlShopping}}/api/v2/offer/quote ou {{urlShopping}}/api/v1/offer/quote
`
{
    "offers": [{
            "journeyKey": "QUR_NDE3Nn4gfn5TRFV_MDQvMjUvMjAyNCAyMToyMH5WQ1B_MDQvMjUvMjAyNCAyMjozMH5_XkFEfjQ5Nzh_IH5_VkNQfjA0LzI1LzIwMjQgMjM6MTB_QlNCfjA0LzI2LzIwMjQgMDA6NDV_fg--",
            "fareKey": "MH5Qfn5BRH5QMTIxWEJHfkJYMjF_fjB_MTQwfn5YITg-"
        }
    ],
    "passengers": [{
            "type": "ADT",
            "count": 1
        }, {
            "type": "CHD",
            "count": 1
        }
    ],
    "promotionCode": "BOSTON"
}
`.
4. Você obterá o resultado com a fareKey diferente do solicitado como no exemplo
![image](https://github.com/voeazul/middleware-b2b/assets/45106624/ddaf3e9c-f9c0-4edd-8eba-b15732dcfe0d)

O que causa divergência da tarifa inicialmente escolhida que seria a MH5Qfn5BRH5QMTIxWEJHfkJYMjF_fjB_MTQwfn5YITg-

Payload do response:

`{
    "data": {
        "order": {
            "journeys": [
			{
                    "designator": {
                        "arrival": "2024-04-26T00:45:00",
                        "origin": "SDU",
                        "destination": "BSB",
                        "departure": "2024-04-25T21:20:00"
                    },
                    "duration": {
                        "hours": 3,
                        "minutes": 25,
                        "days": 0
                    },
                    "fares": {
                        "classOfService": "P",
                        "productClass": "F+",
                        "fareBasis": "P121XBG",
                        "passengerFares": [{
                                "total": 745.2,
                                "charges": [{
                                        "amount": 702.91,
                                        "type": "Fare",
                                        "currencyCode": "BRL"
                                    }, {
                                        "amount": 42.29,
                                        "code": "TXE",
                                        "type": "Tax",
                                        "currencyCode": "BRL"
                                    }
                                ],
                                "passengerType": "ADT"
                            }, {
                                "total": 569.47,
                                "charges": [{
                                        "amount": 527.18,
                                        "type": "Fare",
                                        "currencyCode": "BRL"
                                    }, {
                                        "amount": 42.29,
                                        "code": "TXE",
                                        "type": "Tax",
                                        "currencyCode": "BRL"
                                    }
                                ],
                                "passengerType": "CHD"
                            }
                        ],
                        "key": "MH5Qfn5BRH5QMTIxWEJHfkJYMjF_fjB_MTQwfn5Y"
                    },
                    "stops": {
                        "stopover": 0,
                        "connection": 1
                    },
                    "key": "QUR_NDE3Nn4gfn5TRFV_MDQvMjUvMjAyNCAyMToyMH5WQ1B_MDQvMjUvMjAyNCAyMjozMH5_XkFEfjQ5Nzh_IH5_VkNQfjA0LzI1LzIwMjQgMjM6MTB_QlNCfjA0LzI2LzIwMjQgMDA6NDV_fg--",
                    "segments": [{
                            "designator": {
                                "arrival": "2024-04-25T22:30:00",
                                "origin": "SDU",
                                "destination": "VCP",
                                "departure": "2024-04-25T21:20:00"
                            },
                            "identifier": {
                                "carrierCode": "AD",
                                "flightNumber": "4176"
                            },
                            "international": false,
                            "duration": {
                                "hours": 1,
                                "minutes": 10,
                                "days": 0
                            },
                            "connectionTime": {
                                "hours": 0,
                                "minutes": 0,
                                "days": 0
                            },
                            "legs": [{
                                    "designator": {
                                        "arrival": "2024-04-25T22:30:00",
                                        "origin": "SDU",
                                        "destination": "VCP",
                                        "departure": "2024-04-25T21:20:00"
                                    }
                                }
                            ]
                        }, {
                            "designator": {
                                "arrival": "2024-04-26T00:45:00",
                                "origin": "VCP",
                                "destination": "BSB",
                                "departure": "2024-04-25T23:10:00"
                            },
                            "identifier": {
                                "carrierCode": "AD",
                                "flightNumber": "4978"
                            },
                            "international": false,
                            "duration": {
                                "hours": 1,
                                "minutes": 35,
                                "days": 0
                            },
                            "connectionTime": {
                                "hours": 0,
                                "minutes": 40,
                                "days": 0
                            },
                            "legs": [{
                                    "designator": {
                                        "arrival": "2024-04-26T00:45:00",
                                        "origin": "VCP",
                                        "destination": "BSB",
                                        "departure": "2024-04-25T23:10:00"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            "passengers": [{
                    "fees": [{
                            "code": "DUFEE",
                            "amount": 70.29,
                            "currencyCode": "BRL"
                        }
                    ],
                    "type": "ADT",
                    "key": "MCFBRFQ-"
                }, {
                    "fees": [{
                            "code": "DUFEE",
                            "amount": 52.72,
                            "currencyCode": "BRL"
                        }
                    ],
                    "type": "CHD",
                    "key": "MSFDSEQ-"
                }
            ],
            "organizationCode": "01402750",
            "totals": {
                "discountedAmount": 0,
                "amount": 1437.68,
                "balanceDue": 0
            }
        }
    },
    "notifications": []
}`

**Cenário esperado**

Que a API retorne a tarifa solicitada no endpoint quote

**Ambiente**

Homologação

**Comment by IanLima01022021** [comment]
Boa tarde.
Analisando.

**Comment by IanLima01022021** [comment]
Erika, bom dia.
A farekey retornada no AirSearch é diferente da farekey retornada no Quote e Order, esse é um padrão do meu sistema. Você pode buscar as tarifas no Quote e no Order usando a JourneyKey capturada no retorno do AirSearch.

Sobre a diferença de valor, notamos que era uma configuração no promocode que não deixava aplicar o desconto no Quote e Order, ajustamos e peço que teste novamente por gentileza.

**Comment by erikaaraissaqwe** [comment]
Bom dia, @IanLima01022021 

Notamos que após o ajuste para que não ocorresse a divergência do valor voltamos a ter o erro ISSUE#38, bloqueando nossas reservas internacionais.

Consegue nos ajudar com isso, por favor?

**Comment by IanLima01022021** [comment]
@erikaaraissaqwe, boa tarde.
Podemos falar hoje às 17:30h para testarmos juntos?

**Comment by erikaaraissaqwe** [comment]
Não tenho disponibilidade hoje, podemos conversar amanhã às 14h? Verifiquei que temos um horário agendado.

**Comment by IanLima01022021** [comment]
Erika, boa tarde.
Conforme falamos, foi liberado para sua utilização o promo "azvl" e ele está retornando conforme esperado.
