### ISSUE TITLE
Informação de multa pós embarque ou no-show

### ISSUE THREAD

**Issue by caraujoufsm** [voeazul/middleware-b2b#41]
A Azul hoje não retorna a informação de multa pós embarque ou em caso de no-show .
Por gentileza, vocês teriam previsto essa demanda?

**Comment by lisleyevelin** [comment]
Boa tarde, informado a PO responsável do Projeto Novo Barramento, será criada uma estória que entrará em uma Squad futura.

No response do método: 
GET {{urlResources}}/api/v1/fares 
Implementar no retorno deste método para trazer valor da multa a ser aplicada pós embarque ou no caso de no-show
Não comparecimento(no show) | Qualquer canal R$ 500,00 / US$ 120 / EUR 120ou 100% da tarifa*

**Comment by lisleyevelin** [comment]
https://azuldevops.visualstudio.com/Experiencia%20Digital/_workitems/edit/755612, criada a história.

**Comment by carlos-inacio-voeazul** [comment]
Ajuste priorizado em backlog de desenvolvimento, assim que disponível o mesmo será comunicado na sessão de novidades em nossa documentação disponível aqui no GitHub
