### ISSUE TITLE
Error on /api/v2/airSearch

### ISSUE THREAD

**Issue by diegobernardinelliSAVN** [voeazul/middleware-b2b#43]
When call the new airSearch endpoint (V2). In the response, the promoCode tag has a space.

{
  "data": {
    "airResult": {
      "organizationCode": "57517666",
      "promotionCode ": "AZVL",
      "currencyCode": "BRL",
      "offers": [
        {

**Comment by IanLima01022021** [comment]
Bom dia.
Item corrigido.
