### ISSUE TITLE
Erro ao tentar criar uma reserva

### ISSUE THREAD

**Issue by Andremoreira06** [voeazul/middleware-b2b#44]
**Descrevendo o bug**

Em alguns casos, quando tento criar uma reserva, é me retornado que consegui criar a reserva no state do token, pela POST na rota
"order/api/v1/order" com os dados do passageiro e trecho, e é me retornado um total:

`{
  "data": {
    "order": {
      "totals": {
        "amount": 1276.72,
        "balanceDue": 1276.72
      },
      "currencyCode": "BRL",
      "organizationCode": "01402922"
    }
  }
}`
mas quando vou fazer o checkout com POST na rota "order/api/v1/checkout", é me retornado os erros:

**Erro 1**
`"data":{
                  "notifications":[
                     {
                        "code":"Order.RetrieveRequired",
                        "message":"The requested order was not found or does not exist."
                     }
                  ]
               },
`

**Erro 2**

`"data":{
                  "notifications":[
                     {
                        "code":"Journeys.Duplicated",
                        "message":"Leg already existing in the order."
                     }
                  ]
               },`

**Comportamento esperado**

Conseguir gerar uma reserva

**Ambiente**

Ambiente usado: Produção.

**Contexto adicional**

Sempre criamos um token novo para a criação da reserva, que é usado apenas nesse fluxo.
Esse erro não acontece sempre, mas hoje tivemos um numero expressivo de casos dessa natureza que estão impedindo o fluxo de compra

**Comment by lisleyevelin** [comment]
Bom dia, favor nos enviar os logs em formato .har para análise

**Comment by IanLima01022021** [comment]
Andre, boa tarde.
Continuamos no aguardo dos logs

**Comment by IanLima01022021** [comment]
Boa tarde.
Chamado fechado.
