### ISSUE TITLE
Erro método Payments com methodCode AG

### ISSUE THREAD

**Issue by miguel-infotera** [voeazul/middleware-b2b#45]
**Descrição**
Estou tentando chamar o método */api/v1/order/payments* passando o methodCode como AG igual faziamos na versão antiga, porém não consigo ter sucesso.

**Reproduzir**
3. Estou enviando no endpoint */api/v1/order/payments* o seguinte payload
`{
    "methodCode": "AG",
    "amount": 5735.84,
    "installments": 1,
    "account": "",
    "expirationMonth": 0,
    "expirationYear": 0,
    "holderName": null,
    "verificationCode": null,
    "govId": "17658145025" //um CPF fictício
}`.
4. Se envio um mês aleatório no expirationMonth, recebo o seguinte erro:
`{
    "notifications": [
        {
            "code": "InvalidField.ExpirationYear",
            "message": "The 'ExpirationYear' must be empty when MethodCode is AG"
        }
    ]
}
`
5. Se envio null, recebo o seguinte erro:
`
{
    "errors": {
        "expirationMonth": [
            "Error converting value {null} to type 'System.Int16'. Path 'expirationMonth', line 6, position 27."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-2b545aca9312a27e33a1c90410e73380-8fd58e2c49058d13-00"
}
`
6. Se envio 0, deixa passar. Se envio 0 no expirationYear, recebo o seguinte erro:
`
{
    "error": "An unhandled error has occurred, please enter in contact with technical team with the correlation code.",
    "timestamp": "2024-04-09T13:19:56.8701499+00:00",
    "correlation": "eefe9a66-0a9e-4ec9-b52d-c24252d1f3e7",
    "message": "Index and length must refer to a location within the string. (Parameter 'length')",
    "customData": {},
    "innerException": null,
    "stackTrace": "   at System.String.Substring(Int32 startIndex, Int32 length)\n   at Sales.B2B.Order.Payments.Api.Domain.Commands.v1.OrderPayment.OrderPaymentCommandHandler.<>c__DisplayClass17_0.<ReturnCreditCardByBin>b__1(String x) in /src/Domain/Commands/v1/OrderPayment/OrderPaymentCommandHandler.cs:line 176\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)\n   at Sales.B2B.Order.Payments.Api.Domain.Commands.v1.OrderPayment.OrderPaymentCommandHandler.ReturnCreditCardByBin(String account)\n   at Sales.B2B.Order.Payments.Api.Domain.Commands.v1.OrderPayment.OrderPaymentCommandHandler.Handle(OrderPaymentCommand request, CancellationToken cancellationToken) in /src/Domain/Commands/v1/OrderPayment/OrderPaymentCommandHandler.cs:line 96\n   at Sales.B2B.Order.Payments.Api.Controllers.v1.OrderPaymentsController.<>c__DisplayClass1_0.<<PostOrderPayments>b__0>d.MoveNext() in /src/Api/Controllers/v1/OrderPaymentsController.cs:line 128\n--- End of stack trace from previous location ---\n   at Sales.B2B.Api.Framework.Controllers.v1.BaseController`1.GenerateB2bResponseAsync[TDataObject](Func`1 func, HttpStatusCode responseCode)\n   at Sales.B2B.Order.Payments.Api.Controllers.v1.OrderPaymentsController.PostOrderPayments(OrderPaymentCommand orderPaymentsCommand) in /src/Api/Controllers/v1/OrderPaymentsController.cs:line 129\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Azul.Framework.Api.Middlewares.DeviceHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\n   at Azul.Framework.Api.Middlewares.CultureHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\n   at Azul.Framework.Api.Middlewares.ExceptionHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)"
}
`

**Expected behavior**
Efetuar o pagamento usando a *AgencyAccount*

**Environment**
Environment used: Stage
Source System Language: Java

**Additional context**
Reserva SLKF8A

**Comment by IanLima01022021** [comment]
Miguel, boa tarde.
Validei e o seu escritório possui crédito disponível para utilização no AG, segue abaixo request para pagamento AG, basta colar no body:

{
  "methodCode": "AG",
  "amount": {{orderTotalBalanceDue}},
   "installments": 1
}
