### ISSUE TITLE
Diferença de valores na busca de disponibilidade entre o ADT e CHD

### ISSUE THREAD

**Issue by Guuhti** [voeazul/middleware-b2b#47]
Quando realizamos a busca de disponibilidade, notamos que existe uma diferença na tarifa quando o viajante é um adulto (ADT) e criança (CHD). Na busca estamos aplicando o código de acordo.

![image](https://github.com/voeazul/middleware-b2b/assets/58939778/95f51330-2f5b-4f22-aca2-669ac7edca01)

Estamos usando o ambiente de homologação.

Gostaríamos de saber se está correta a informação de tarifas entre o ADT e CHD sendo elas diferente em alguns resultados?

Estaremos enviando os Logs para análise por email.

**Comment by IanLima01022021** [comment]
Gustavo, boa tarde.
Qual o loc dessa reserva?

**Comment by Guuhti** [comment]
Não foi realizado a reserva, Ian. Esse cenário está acontecendo na busca de disponibilidade do retorno do AirSearch.

**Comment by IanLima01022021** [comment]
Gustavo, 
Pode por gentileza efetivar a reserva e mandar os logs por email, com a reserva conseguimos ver no sistema a divergência.

**Comment by Guuhti** [comment]
Ian, boa tarde!
Enviei os logs conforme solicitado. o localizador é: YWHL9H

**Comment by IanLima01022021** [comment]
Gustavo, boa tarde.
Na tarifa do CHD está aplicando um desconto que não aplicamos em produção, a base teste está desatualizada. Pode considerar sempre o valor que retorna no total pois ali está correto. Já pedi para o time responsável retirar o desconto em base teste para facilitar o entendimento.
