### ISSUE TITLE
Enviar dois promotionCode no mesmo ShoppingAirSearchRQ

### ISSUE THREAD

**Issue by miguel-infotera** [voeazul/middleware-b2b#48]
**Problema**
Meu problema é que eu alguns dos nossos clientes usam mais de um promotionCode, gostaria de enviar dois promotionCode em uma chamada

**Solução**
Gostaria de enviar mais de um promotionCode na requisição do método ShoppingAirSearchRQ. Gostaria que o campo promotionCode fosse uma lista de Strings.

**Solução alternativa**
Uma alternativa seria aceitar enviar vários promotionCodes no mesmo campo porém separados por algum caractere como " , " ou " ; ".

**Comment by lisleyevelin** [comment]
Boa tarde, 
Infelizmente a nossa API não está preparada para receber mais de um promotionCode, e NÃO existe a possibilidade de implementação sobre isso.
