### ISSUE TITLE
Como saber se o promotionCode foi aplicado com sucesso ou não - Método ShoppingAirSearchRQ

### ISSUE THREAD

**Issue by miguel-infotera** [voeazul/middleware-b2b#49]
É possível saber se o promotionCode que eu enviei na requisição do ShoppingAirSearchRQ foi aceito ou não?

Gostaria de saber se o preço que foi retornado está com o desconto ou não para informarmos ao cliente.

**Comment by lisleyevelin** [comment]
Bom dia, Miguel
Tudo bem com você?

Disponibilizamos uma nova versão no Swagger e também no ambiente de testes dos métodos:
Shopping
POST {{urlShopping}}/api/v2/airSearch
POST {{urlShopping}}/api/v2/offer/quote
Order
{{urlOrder}}/api/v2/order
Estes métodos irão retornar o valor aplicado pelo PromotionCode, com no exemplo abaixo:
 "passengerFares": [
                            {
                                "passengerType": "ADT",
                                "count": 1,
                                "total": 1291.47,
                                "charges": [
                                    {
                                        "amount": 2526.9,
                                        "type": "Fare",
                                        "currencyCode": "BRL"
                                    },
                                    {
                                        "amount": 28.02,
                                        "type": "TaxSum",
                                        "currencyCode": "BRL"
                                    },
                                    {
                                        "amount": -1263.45,
                                        "type": "PromotionDiscount",
                                        "currencyCode": "BRL"
                                    }
 
Peço atualizar os métodos pois os mesmos irão te ajudar na identificação se o promotionCode foi aplicado.
