### ISSUE TITLE
Error AlreadyExistsInState

### ISSUE THREAD

**Issue by dani-or** [voeazul/middleware-b2b#50]
**Describe the bug**
I can not create a order while there is another order in progress

**To Reproduce**
1. an user is trying to book POST token -> POST authenticate -> POST airSearch -> POST quote -> POST order
2. In paralell another user tries to create a different order with the same flow (but this time without generating token) POST airSearch -> POST quote -> POST order (the user #1 has not finished yet their booking), the second user gets the error 
{
    "notifications": [
        {
            "code": "RequestFailed.Order.AlreadyExistsInState",
            "message": "There is already an order created in state."
        }
    ]
}

**Expected behavior**
the user # 2 should be able to create another order

**Environment**

Environment used: Stage 
Source System Language: I am testing with Postman

**Additional context**
I would like to understand why the user #2 can not create an order until the user #1 finish their transaction,

Are the service POST order, POST payment  and POST checkout saving the state?
can I create multiple order at the same time for diferent user?
Is there any way to user the service in an stateless way? 
should I just allow a transation at time?
thanks for all the information that you can provider regarding the state of the services and the concurrence.

**Comment by IanLima01022021** [comment]
Dani, good afternoon.
Each token contains a login, if you have more than one user, another token will be required. It is not possible for the same token to have more than one login.
