### ISSUE TITLE
Cancelar toda a reserva

### ISSUE THREAD

**Issue by miguel-infotera** [voeazul/middleware-b2b#51]
Seria possível criar um método para cancelar toda a reserva ao invés de cancelar por Journey?

**Comment by IanLima01022021** [comment]
Miguel, bom dia.
Agradeço a sugestão mas no momento não será possível aplicar essa atualização na nossa estrutura.

Futuramente trataremos as melhorias e iremos considerar a sua sugestão.

Obrigado!
