### ISSUE TITLE
Informação do bilhete dos passageiros no método GET order

### ISSUE THREAD

**Issue by miguel-infotera** [voeazul/middleware-b2b#54]
Essa issue é uma pergunta.

Gostaria de saber onde vem a informação dos bilhetes dos passageiros depois de serem emitidos os bilhetes.

**Comment by lisleyevelin** [comment]
Miguel, a Azul não trabalha com bilhetes. 
Existe a criação da reserva ou seja PNR e dentro desta reserva consta os passageiros.

**Comment by lisleyevelin** [comment]
Exatamente isso, você pode considerar a identificação do passageiro neste campo, exemplo:
      "passengers" : [ {
        "key" : "MCFBRFQ-",
        "type" : "ADT",
